update changes in 4 files for nc-news-5
AndyBeeee/nc-news pull request #4
Opened 2023-06-27 13:29 UTC by AndyBeeee

2023-06-27 13:52 UTC, EddTheDuck requested changes
If you could please make your tests a bit more robust and then re-submit.

Thanks!

2023-06-27 13:52 UTC, EddTheDuck commented on __tests__/test.test.js
> +            expect(body.articles[6]).toMatchObject({
You should check each article matches rather just one. Consider using a forEach.

2023-06-27 13:52 UTC, EddTheDuck commented on __tests__/test.test.js
> +            expect(sorted).toBe(true)
Have a look at jest-sorted which will make testing for the order of things a lot easier.

https://www.npmjs.com/package/jest-sorted

2023-06-28 08:01 UTC, RichardNeat approved these changes
Nice one Andy! A couple of suggested changes down below :)

2023-06-28 08:01 UTC, RichardNeat commented on __tests__/test.test.js
> +    })
You could - if you wanted to - include a test to ensure you aren't getting the response body back. Totally optional if you wanted to be explicit.

2023-06-28 08:01 UTC, RichardNeat commented on db/models/articles.model.js
> +
Cool solution here Andy - we could have achieved this using SQL queries and aggregate functions to get the comment_count column. Have a go at refactoring to that if you want to. Would look a bit nicer :)

2023-06-28 08:08 UTC, merged